permissions:
  contents: write

name: Release

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.13.0

      - run: zig build test
      - run: zig build -Doptimize=ReleaseSafe
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./zig-out/bin/zig-wordle
          asset_name: zigle
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my latest application build"
